version: "3"

services:
    dev:
        image: node:10.15.1
        volumes:
            - ./:/srv
        working_dir: /srv
        command: npm run start
        ports:
            - 8080:8080
        